src/components/BottomNavBar/index.tsx, src/components/BottomNavBarItem/index.tsx, src/components/EndUserBottomNavBar/index.tsx
PR for https://github.com/Builder-s-League/BuildersLeague-Edition1/issues/2
=> [1|End-user Navbar] Breadboard

package-lock.json, src/app/forgotPassword/page.tsx, src/app/mylogin/page.tsx, src/app/page.tsx
Issue Number: 24
I made a Login Page and linked it to a Forgot Password page.
=> Made breadboard for login page and forgot password

.husky/pre-commit, package-lock.json, package.json, src/app/page.tsx, src/app/setting/app-domain/page.tsx, src/app/setting/app-tour/page.tsx, src/app/setting/blob-storage/page.tsx, src/app/setting/page.tsx, src/app/setting/update-email/page.tsx
=> Settings page added

src/app/feed/page.tsx, src/components/PostCard/index.tsx
=> [1|Feed Page] Breadboard

src/components/NavBar/CBHNavbar.tsx, src/components/NavBar/HRNavbar.tsx, src/components/NavBar/Narbar-button.tsx
Issue = [1|CBH & HR - Nav Bar] Breadboard #83
Basic HTML and CSS used
=> CBH and HR nav bar created

src/app/surveydash/page.tsx, src/components/NewSurvey.tsx
=> [1|CBH - Survey Dashboard & Add Survey] Breadboard #73

src/app/about/page.tsx, src/components/Header.tsx
[1|About Page] Breadboard
Closes #51
=> [1|About Page] Breadboard

src/app/notes/page.style.css, src/app/notes/page.tsx
Added note page breadboard with simple css
=> added note page breadboard an simple styles

src/app/globals.css, src/app/new-article-post/page.tsx
PR request for #60
fixed article link 
added route for article posts 
CSS does not work for safari
=> [1|CBH - New Article Post] Breadboard

src/app/cbh/login/page.tsx, src/app/hr/login/page.tsx, src/components/login-form/index.tsx
=> [1|CBH & HR - Login Page] Breadboard

src/app/employee/page.tsx, src/components/EmployeeDashboard/EmployeeCard.tsx, src/components/EmployeeDashboard/PageButton.tsx
=> [1|CBH & HR - Employee Dashboard Page] Breadboard

src/app/about/page.tsx, src/components/VideoEmbed.tsx
=> [2|About Page] About Page #52

src/components/NewSurvey.tsx
Previous Layout
Updated Layout
=> [BUG] Style Fix: CBH Survey Dashboard - New Survey Form

src/app/cbh/setting/page.tsx, src/app/cbh/setting/update-email/page.tsx
Worked on CSS and buttons
functionality for updating email and phone number works, just have to configure for prod.
=> Set up settings plus email and phone

src/app/hr/settings/page.tsx
Updated version of issue #90 to enssure there is no error with the current main branch
=> [2|HR - Setting Page] Update Organization information #90

package-lock.json, src/app/cbh/employee/add/page.tsx, src/app/cbh/employee/page.tsx, src/components/OrganizationCBH/index.tsx
This PR includes front-end completed with the functioning fields and email validation.
Add functionality to database still pending.
=> [2|CBH & HR - Employee Dashboard Page] Add an employee #40

src/app/cbh/organization-dashboard/add/page.tsx, src/app/cbh/organization-dashboard/edit/[id]/page.tsx
=> Database Integration: Add new organization #34

package-lock.json, package.json, src/app/(employees)/emp/resources/page.tsx, src/components/ResourceContentTip/index.tsx
PR for #14 
- Added component for a tooltip when the user selects the content inside of our resource page.
- Added functionality to the copy button
Output: "This is the resource"
=> [5|Resource Page (Item) and Note Taking Feature] The tooltip 

src/app/cbh/setting/page.tsx
=> CBH- Settings UI

src/app/contact-us/page.tsx
Styled "/contact-us" and created functionallity for "go back" button
=> Style bunty for contact-us page

src/app/hr/feedback/page.tsx, src/app/hr/settings/page.tsx
Updated settings HR page to link to the feedback
Created the Feedback page for HR
=> [5|HR - Setting Page] Feedback #87

src/app/topic/[id]/page.tsx, src/components/MenuDrawer/index.tsx
Style bounty:
http://localhost:3000/topic/1
Is not using the Hamburger menu
=> Style bounty Update Hamburger button Topic page

src/app/cbh/survey-dash/page.tsx, src/components/CellPopup.tsx, src/components/NewSurvey.tsx, src/types/survey.ts, supabase/migrations/20241005210615_init.sql
#74 
contributor: @Sneezyw @Simonwmm
=> [2|CBH - Survey Dashboard & Add Survey] Survey tables #74

src/app/(employees)/emp/page.tsx, src/app/cbh/page.tsx, src/app/hr/page.tsx, src/app/page.tsx, src/components/NavBar/CBHNavbar.tsx, src/components/NavBar/HRNavbar.tsx, src/components/ProfileSetting.tsx
fixed Nav bar CSS
added CSS to navigation
=> Added Tailwind CSS

.env.example, README.md, src/components/ProfileSetting.tsx
Hi Diogo, we have finished the CUD profile information feature, here are some screenshots of it, we also did a validation of email and contact info
Issue linked: #19
=> [2|Profile Setting Page] CUD profile information pull request

README.md, src/app/emp/(authenticated)/change-password/page.tsx, src/components/ChangePassword/index.tsx, src/components/ProfileSetting.tsx
#228 Created a change password page for employee profile settings.This ticket creates the frontend but the backend part #21.
=> created a change password page and set up the routing.

.env.example, package-lock.json, src/app/emp/(authenticated)/topics/[topicId]/_page/index.tsx, src/app/emp/(authenticated)/topics/[topicId]/resource/[resourceId]/page.tsx, src/app/emp/(authenticated)/topics/page.tsx, src/components/MenuDrawer/index.tsx, src/components/ResourceAddNote/index.tsx
=> Fixed top left sidebar for topics

src/app/login/actions.ts, src/app/login/page.tsx, src/middleware.ts
- Improve login page with loading state and error handling
- Update server-side login action to fetch and return user role
- Modify middleware to handle authentication and role-based routing
- Add client-side role-based redirection after successful login
- Remove verbose logging and simplify authentication checks
@iKostubh
=> refactor: enhance login and authentication flow
